# Site settings
title:          Scorefold Devlog
description:    "News and updates around the development of scorefold."
url:            https://www.scorefold.com

# Author
author:
  name:         Lukas Plechinger
  email:        lukas@scorefold.com
  url:          https://www.plechinger.at/

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  #github: https://github.com/inelaah
  #twitter: https://twitter.com/plechine
  #linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
